name: Create Release Notes

on:
  release:
    types: [created]

permissions: {}

env:
  GO_VERSION: '1.25'

jobs:
  create-release-notes:
    name: release-notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.TESEO_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          gh release edit "$TAG_NAME" \
            --title "$TAG_NAME" \
            --notes-file "${{ github.workspace }}/.changes/${TAG_NAME}.md" \
            --latest
